# Generated by Django 2.0 on 2017-12-24 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquetipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('torneosGanadosLocal', models.IntegerField()),
                ('torneosGanadosInternacional', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passCode', models.IntegerField()),
                ('nombreEspanol', models.CharField(max_length=250)),
                ('nombreIngles', models.CharField(max_length=250)),
                ('tipoCarta', models.CharField(max_length=2)),
                ('atributo', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
                ('tipoMonstruo', models.CharField(max_length=50)),
                ('nivel', models.IntegerField()),
                ('ataque', models.IntegerField()),
                ('defensa', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=250)),
                ('arquetipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohShop.Arquetipo')),
            ],
        ),
        migrations.CreateModel(
            name='CartaXOrigen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rareza', models.CharField(max_length=50)),
                ('idCarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohShop.Carta')),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('fechaLanzamiento', models.DateTimeField()),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoProducto', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('fechaIngreso', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='otros',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohShop.Producto'),
        ),
        migrations.AddField(
            model_name='cartaxorigen',
            name='idOrigen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohShop.Origen'),
        ),
        migrations.AddField(
            model_name='carta',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yugiohShop.Producto'),
        ),
    ]
